#!/bin/env -S just --justfile

# create and edit a new day
day day=`date +%d`: (newday day)
    $EDITOR "./src/day{{ day }}.rs"

[private]
newday day:
    [ -f "./src/day{{ day }}.rs" ] || jinja2 \
        -D "day={{ day }}" \
        ./day_template.rs.j2 \
        -o "./src/day{{ day }}.rs"
    # cursed
    grep 'mod day{{ day }};' ./src/lib.rs || \
        sed -i 's/aoc_lib/mod day{{ day }};\naoc_lib/' ./src/lib.rs
