#!/usr/bin/bash

for i in aoc2019py/*/; do
    (
        cd "$i" || exit 1
        printf "\n==================\n"
        printf "Testing %s...\n" "$i"
        python3.8 test.py || exit 1
    )
done

printf "================================\n"
printf "All tests successful. Pushing...\n"
printf "================================\n"
